#!/bin/bash

REAL_PWD="$(realpath "$PWD")"
MOUNTED_DIR="/${REAL_PWD##*/}"
PI_HOME="/home/pi"

mkdir -p "$HOME/.pi/agent"

HAS_P_FLAG=false
for arg in "$@"; do
  if [[ "$arg" == "-p" ]]; then
    HAS_P_FLAG=true
    break
  fi
done

TTY_FLAGS=()
[[ -t 0 ]] && TTY_FLAGS+=(-i)
[[ -t 1 ]] && TTY_FLAGS+=(-t)

MOUNT_OPT=""
[[ "$(uname)" == "Darwin" ]] && MOUNT_OPT=":cached"

DOCKER_ARGS=(
  --rm
  --init
  "${TTY_FLAGS[@]}"
  --user "$(id -u):$(id -g)"
  -e "TERM=${TERM:-xterm-256color}"
  -e "LANG=${LANG:-en_US.UTF-8}"
  -v "$HOME/.agents:$PI_HOME/.agents"
  -v "$HOME/.gitconfig:$PI_HOME/.gitconfig:ro"
  -v "$HOME/.gitignore_global:$PI_HOME/.gitignore_global:ro"
  -v "$HOME/.pi/agent:$PI_HOME/.pi/agent"
  -v "pi-packages:$PI_HOME/.pi/packages"
)

[[ -n "$LC_ALL" ]] && DOCKER_ARGS+=(-e "LC_ALL=$LC_ALL")
[[ -n "$COLORTERM" ]] && DOCKER_ARGS+=(-e "COLORTERM=$COLORTERM")

if [[ "$REAL_PWD" == "$HOME" ]]; then
  if [[ "$HAS_P_FLAG" == true ]]; then
    MOUNTED_DIR="$PI_HOME"
  else
    echo "Warning: running from HOME directory! Only non interactive mode with -p flag supported from HOME directory" >&2
    exit 1
  fi
else
  DOCKER_ARGS+=(-v "$REAL_PWD:$MOUNTED_DIR$MOUNT_OPT")
fi

DOCKER_ARGS+=(
  -e "MISE_CEILING_PATHS=$MOUNTED_DIR"
  -w "$MOUNTED_DIR"
  "ghcr.io/andrcuns/pi-docker:0.70.6"
)

exec docker run "${DOCKER_ARGS[@]}" "$@"
